---
# tasks file for python3_centos

- name: Install IUS repo
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: upgrade all packages
  yum: name=* state=latest

- name: install python3
  yum: 
    name: python36u
    state: present

- name: install python36u-libs
  yum:
    name: python36u-libs
    state: present

- name: install python36u-devel
  yum:
    name: python36u-devel
    state: present

